name: Coverage

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci
              working-directory: "Vevox Chatroom"

            - name: Run tests with coverage
              run: npx nyc --reporter=text npm test
              working-directory: "Vevox Chatroom"

            - name: Upload coverage to Coveralls (optional)
              if: ${{ secrets.COVERALLS_REPO_TOKEN != '' }}
              run: |
                  npm install --no-save coveralls@^3 --no-audit --no-fund
                  npx nyc report --reporter=text-lcov | npx coveralls --repo-token=${{ secrets.COVERALLS_REPO_TOKEN }}
              working-directory: "Vevox Chatroom"
