name: Update Contributor Graph (avatars)

on:
    push:
        branches: ["**"]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-contributors:
        runs-on: ubuntu-latest
        env:
            README_PATH: README.md
            DETAILS_SUMMARY_TEXT: "<summary>Contributor Graph</summary>"
            START_MARKER: "<!-- CONTRIBUTORS:START -->"
            END_MARKER: "<!-- CONTRIBUTORS:END -->"
            AVATAR_SIZE: "48" # px
            MAX_CONTRIBUTORS: "200" # safety cap

        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Refresh contributor avatars in README
              run: node .github/scripts/update-contributors.js
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN || secrets.GITHUB_TOKEN }}

            - name: Commit & push if changed
              env:
                  PAT_OR_TOKEN: ${{ secrets.PERSONAL_TOKEN || secrets.GITHUB_TOKEN }}
                  README_PATH: README.md
              run: |
                  if git diff --quiet -- "${README_PATH}"; then
                    echo "No changes."
                    exit 0
                  fi
                  git config user.name  "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add "${README_PATH}"
                  git commit -m "docs: refresh Contributor Graph avatars"
                  git push https://x-access-token:${PAT_OR_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF_NAME:-main} || \
                  git push https://x-access-token:${PAT_OR_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main || \
                  git push https://x-access-token:${PAT_OR_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:master
